apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s-app
  template:
    metadata:
      labels:
        app: go-k8s-app
    spec:
      containers:
        - name: go-k8s-app
          image: go-k8s-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-k8s-app-service
spec:
  type: NodePort
  selector:
    app: go-k8s-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

